### ISSUE TITLE
Problem with non-ANSI characters in LCD.xml

### ISSUE THREAD

**Issue by grzechj** [herrnst/script.xbmc.lcdproc#54]
I have degree symbol (°) in my LCD.xml definition. After I have upgraded to LibreElec 9.0.0 (which caused the addon to upgrade to) I'm getting:
```
14:33:40.494 T:1681830768   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xb0' in position 52: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.xbmc.lcdproc/main.py", line 33, in <module>
                                                xbmclcd.RunLCD()
                                              File "/storage/.kodi/addons/script.xbmc.lcdproc/resources/lib/xbmclcdproc.py", line 103, in RunLCD
                                                self._LCDproc.Render(settingsChanged)
                                              File "/storage/.kodi/addons/script.xbmc.lcdproc/resources/lib/lcdbase.py", line 542, in Render
                                                line = self.m_InfoLabels.GetInfoLabel(self.m_lcdMode[mode][inLine]['text'])
                                              File "/storage/.kodi/addons/script.xbmc.lcdproc/resources/lib/infolabels.py", line 54, in GetInfoLabel
                                                ret = xbmc.getInfoLabel(strLabel)
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xb0' in position 52: ordinal not in range(128)
                                            -->End of Python script error report<--
```

**Comment by herrnst** [comment]
Could you please check and verify that the issue is fixed using the utflabel branch (see https://github.com/herrnst/script.xbmc.lcdproc/tree/utflabel) ?

**Comment by grzechj** [comment]
It works ok with this version. Thanks!

sob., 2 mar 2019 o 10:14 Daniel Scheller <notifications@github.com>
napisał(a):

**Comment by herrnst** [comment]
Thanks, will release this as 3.0.4 then.
