### ISSUE TITLE
xbmc-lcdproc stopped working on ubuntu focal with kodi 19

### ISSUE THREAD

**Issue by zeus86** [herrnst/script.xbmc.lcdproc#59]
since 3 days or so i am encountering the following issue:
* lcd went blank (but backlighted [hd44780])
* on reboot only the welcome message from LCDd is shown
* the lcdproc-plugin crashes when trying to (re-)enable it

i am using ubuntu focal 20.04 with unattended upgrades enabled (but there have not been updated any stuff lately which might relate to this IMHO) with kodi `2:19.0+git20200806.0307-da34f16569-0focal` and lcdproc `0.5.9-3` from the ubuntu repos (recompiled from the ubuntu sources to get proper hd44780 support with LCD2USB).
the lcdproc plugin is `v3.90.1`

from the log:
``` 
2020-09-17 22:41:05.479 T:866      INFO <general>: initializing python engine.
2020-09-17 22:41:06.677 T:857     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'xbmcvfs' has no attribute 'translatePath'
                                                   Traceback (most recent call last):
                                                     File "/home/kodi/.kodi/addons/script.xbmc.lcdproc/main.py", line 27, in <module>
                                                       from resources.lib.xbmclcdproc import XBMCLCDproc
                                                     File "/home/kodi/.kodi/addons/script.xbmc.lcdproc/resources/lib/xbmclcdproc.py", line 36, in <module>
                                                       from .lcdproc import *
                                                     File "/home/kodi/.kodi/addons/script.xbmc.lcdproc/resources/lib/lcdproc.py", line 33, in <module>
                                                       from .lcdbase import *
                                                     File "/home/kodi/.kodi/addons/script.xbmc.lcdproc/resources/lib/lcdbase.py", line 41, in <module>
                                                       __lcdxml__        = xbmcvfs.translatePath(os.path.join("special://masterprofile", "LCD.xml"))
                                                   AttributeError: module 'xbmcvfs' has no attribute 'translatePath'
                                                   -->End of Python script error report<--
                                                   
2020-09-17 22:41:06.722 T:857      INFO <general>: Python interpreter stopped
```
stuff, which is usually displayed, controlled by the advanedsettings (looks wierd, but yes, i am using a 40x2 display):
```
 <lcd>
  <heartbeat>false</heartbeat>            
  <scrolldelay>3</scrolldelay>            
  <rows>2</rows>
  <columns>40</columns>
 </lcd>
```
and last but not least: my LCD.xml:
```
<lcd>
  <disableonplay></disableonplay>
  <disableonplaydelay>0</disableonplaydelay>
  <scrollseparator>+++</scrollseparator>
  <progressbarsurroundings>on</progressbarsurroundings>
  <allowemptylines>off</allowemptylines>
  <extrabar1>progress</extrabar1>
  <extrabar2>volume</extrabar2>
  <centerbigdigits>on</centerbigdigits>
  <navigation>
     <line>$INFO[System.CurrentWindow] -> $INFO[System.CurrentControl]</line>
     <line>$INFO[LCD.AlignCenter] $INFO[System.Time(HH:MM:SS)] - $INFO[System.Date(dd MMM yyyy)]</line>
  </navigation>
  <music>
     <line>$INFO[LCD.PlayIcon] $INFO[LCD.AlignCenter] $INFO[MusicPlayer.Artist] - $INFO[MusicPlayer.Title]</line>
     <line>$INFO[LCD.ProgressBar] $INFO[LCD.ProgressBar]</line>
 <!--    <line>$INFO[LCD.ProgressBar]</line> -->
  </music>
  <video>
     <line>$INFO[LCD.AlignCenter] $INFO[Player.Title]</line>
     <line>$INFO[LCD.ProgressBar]</line>
  </video>
 <tvshow>
     <line>$INFO[LCD.AlignCenter] $INFO[VideoPlayer.TVShowTitle] - $INFO[Player.Title]</line>
     <line>$INFO[LCD.ProgressBar]</line>
  </tvshow>
 <general>
    <line>KODI running...</line>
    <line>$INFO[LCD.AlignCenter] $INFO[System.Time(HH:MM:SS)] - $INFO[System.Date(dd MMM yyyy)]</line>
 </general>
  <screensaver>
    <line>$INFO[LCD.TimeWide21]</line>
    <line>$INFO[LCD.TimeWide22]</line>
  </screensaver>
<!--  <xbelaunch>
    <line>Playing</line>
    <line>$INFO[System.LaunchXBE]</line>
  </xbelaunch>
  <pvrtv>
     <line>$INFO[VideoPlayer.ChannelName]</line>
     <line>$INFO[VideoPlayer.Title]</line>
  </pvrtv>
  <pvrradio>
     <line>$INFO[MusicPlayer.ChannelName]: $INFO[MusicPlayer.Title]</line>
     <line>$INFO[LCD.ProgressBar]</line>
  </pvrradio> -->
</lcd>
```

let me know if i can provide any useful additional info.

**Comment by herrnst** [comment]
xbmc.translatePath is deprecated as of https://github.com/xbmc/xbmc/commit/5e30ddf72403470eec8a41d16be2cce3a92e6568 and moved into xbmcvfs. You either need to update your Kodi to at least that commit, or downgrade script.xbmc.lcdproc.

**Comment by zeus86** [comment]
ah, yes, i see, obviously my unattended upgrades did not update packages from PPAs, so kodi itself left as is (even if that release was not that old..). anyway, thanks for pointing this out, upgrading kodi finally did the trick.
