### ISSUE TITLE
hd44780-a01 and hd44780-a02 does not work anymore

### ISSUE THREAD

**Issue by ghtester** [herrnst/script.xbmc.lcdproc#65]
Encountered on RPi 4B/2GB after upgrade LibreELEC Nightly from 20220212.

2022-02-15 01:48:05.466 T:3457 INFO <general>: initializing python engine.
2022-02-15 01:48:06.218 T:3457 INFO <general>: ### [XBMC LCDproc] - Connected to LCDd at 127.0.0.1:13666, Protocol version 0.4 - Geometry 16x2 characters (80x16 pixels, 5x8 pixels per character)
2022-02-15 01:48:06.247 T:3457 INFO <general>: ### [XBMC LCDproc] - Empty driver information reply
2022-02-15 01:48:06.389 T:3457 INFO <general>: ### [XBMC LCDproc] - Loading settings from /storage/.kodi/addons/script.xbmc.lcdproc/resources/LCD.xml.defaults
2022-02-15 01:48:06.395 T:3457 INFO <general>: ### [XBMC LCDproc] - Loading settings from /storage/.kodi/userdata/LCD.xml
2022-02-15 01:48:06.705 T:3457 ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'LookupError'>
Error Contents: unknown encoding: hd44780-a02
Traceback (most recent call last):
File "/storage/.kodi/addons/script.xbmc.lcdproc/main.py", line 33, in <module>
xbmclcd.RunLCD()
File "/storage/.kodi/addons/script.xbmc.lcdproc/resources/lib/xbmclcdproc.py", line 103, in RunLCD
self._LCDproc.Render(settingsChanged)
File "/storage/.kodi/addons/script.xbmc.lcdproc/resources/lib/lcdbase.py", line 550, in Render
self.SetLine(mode, outLine, line, self.m_lcdMode[mode][inLine], bForce)
File "/storage/.kodi/addons/script.xbmc.lcdproc/resources/lib/lcdproc.py", line 575, in SetLine
bstrScrollMode = self.m_Settings.getLCDprocScrollMode().encode(self.m_strLCDEncoding)
LookupError: unknown encoding: hd44780-a02
-->End of Python script error report<--
2022-02-15 01:48:06.740 T:3457 INFO <general>: Python interpreter stopped

I am using HD44780 compatible LCD display 16x2, connected through i2c bus. Working fine except the alternate charsets A01 and A02 can't be configured anymore.

**Comment by herrnst** [comment]
Thanks for the report. This should be fixed in the "codec" branch (at least with these changes I cannot reproduce it anymore). Can you please test and confirm with https://github.com/herrnst/script.xbmc.lcdproc/tree/codec ?

**Comment by ghtester** [comment]
Thanks a lot for the fix, I can confirm the charsets A00 and A02 can be configured again.

**Comment by herrnst** [comment]
Thanks for checking and your feedback. Will merge the commits to master and release a fixed version for distribution through the addon repo this week.
